# Copyright (c) 2024-2025 Voyant Photonics, Inc.
#
# This example code is licensed under the MIT License.
# See the LICENSE file in the repository root for full license text.

/**:
  ros__parameters:
    # These are the standard parameters for local testing in loopback mode:
    # - "0.0.0.0:4444": Local binding address and port
    # - "224.0.0.0": Multicast group address
    # - "127.0.0.1": Interface address (localhost/loopback)
    #
    # When connecting to an actual sensor
    #  - "0.0.0.0:8080": Binds to all interfaces on port 8080
    #  - "224.0.0.0": Standard multicast group address for the sensor
    #  - "192.168.1.100": Your network interface's IP address
    binding_address: '0.0.0.0:4444'
    multicast_group: '224.0.0.0'
    interface_address: '127.0.0.1'
    spn_filter: false # Enable Single Point Noise filter

    # timestamp_mode[optional]
    # - TIME_FROM_SENSOR
    # - TIME_FROM_ROS
    timestamp_mode: 'TIME_FROM_ROS'

    frame_id: 'voyant_sensor'
